### ISSUE TITLE
Responsiveness of the site

### ISSUE THREAD

**Issue by soshar** [HackVerse/2023#30]
The website must be made responsive

@syedabdulgafoor

**Comment by syedabdulgafoor** [comment]
Hey take a chil pill my phone was damaged:)

**Comment by samyaksand** [comment]
Hi @Sharvani2002 
I tried to make the website responsive. Could you check my PR #33

**Comment by soshar** [comment]
@samyaksand great, I have checked your PR. The issue with "about" page still persists: 
- The logo covers content
- The green button has got covered

In the home page, the box with hackathon information can be positioned slightly higher.
Can you fix these issues?

**Comment by soshar** [comment]
The site has been made responsive by @saikiranpatil.
