### ISSUE TITLE
Add google maps location of NITK in the footer

### ISSUE THREAD

**Issue by soshar** [HackVerse/2023#64]
Something like this:
https://clash-of-codes.netlify.app/

**Comment by somu5307** [comment]
I want to contribute to this issue. Is it still open?

**Comment by soshar** [comment]
Yes, it's open

**Comment by somu5307** [comment]
<img width="946" alt="image" src="https://user-images.githubusercontent.com/83502676/227758806-44bf16d5-adda-4dbe-acec-cae70fdf7d6d.png">
do i have to replace the available svkm's dwarakadas location with nitk location or what?
Can you please explain it to me.

**Comment by soshar** [comment]
Yes, you have to change the location to that of [NITK, surathkal](https://goo.gl/maps/RkZCZ236RNrX6Tn3A). Also, Please try adjusting the position of other elements in the footer since you are adding the maps now.

**Comment by somu5307** [comment]
I have made relevant changes, but i couldn't find the .html that need to be edited in this respo.
<img width="960" alt="image" src="https://user-images.githubusercontent.com/83502676/227825421-af08ef7d-54df-4749-a347-0a6b478d6890.png">

**Comment by soshar** [comment]
@somu5307  You can make the changes in the footer part of [index.html](https://github.com/HackVerse/hackverse.github.io/blob/main/index.html)
![image](https://user-images.githubusercontent.com/55979861/227851933-eaa141d6-2569-4e6f-ba71-cc8b0df4ff60.png)

Please fork the repo, add your changes and create a PR for this repo

**Comment by soshar** [comment]
Good work @somu5307
